/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MintGrindNFTInterface extends Interface {
    getFunction(nameOrSignature: "TARGET_CHAIN_ID" | "acceptedTokens" | "approve" | "balanceOf" | "canMint" | "getApproved" | "getMintedCount" | "getRemainingMints" | "isApprovedForAll" | "maxPerWallet" | "maxSupply" | "mint" | "mintPrice" | "mintedPerWallet" | "name" | "nonces" | "owner" | "ownerOf" | "pause" | "paused" | "paymentToken" | "recoverNative" | "recoverToken" | "remainingSupply" | "renounceOwnership" | "safeTransferFrom(address,address,uint256)" | "safeTransferFrom(address,address,uint256,bytes)" | "setApprovalForAll" | "setMaxSupply" | "setMintPrice" | "setPaymentToken" | "setTokenAcceptance" | "signer" | "supportsInterface" | "symbol" | "tokenURI" | "totalSupply" | "transferFrom" | "transferOwnership" | "unpause" | "usedHashes"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "ApprovalForAll" | "ConsecutiveTransfer" | "MaxSupplyUpdated" | "MintPriceUpdated" | "Minted" | "OwnershipTransferred" | "Paused" | "PaymentTokenUpdated" | "TokenAcceptanceUpdated" | "Transfer" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'TARGET_CHAIN_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptedTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'canMint', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMintedCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRemainingMints', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'maxPerWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, string, string, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintedPerWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverNative', values?: undefined): string;
encodeFunctionData(functionFragment: 'recoverToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'remainingSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256)', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMaxSupply', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMintPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPaymentToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTokenAcceptance', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'signer', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedHashes', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'TARGET_CHAIN_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canMint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMintedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemainingMints', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintedPerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverNative', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recoverToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'remainingSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom(address,address,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMintPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenAcceptance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedHashes', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, approved: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
      export interface OutputObject {owner: string, approved: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ApprovalForAllEvent {
      export type InputTuple = [owner: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [owner: string, operator: string, approved: boolean];
      export interface OutputObject {owner: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConsecutiveTransferEvent {
      export type InputTuple = [fromTokenId: BigNumberish, toTokenId: BigNumberish, from: AddressLike, to: AddressLike];
      export type OutputTuple = [fromTokenId: bigint, toTokenId: bigint, from: string, to: string];
      export interface OutputObject {fromTokenId: bigint, toTokenId: bigint, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MaxSupplyUpdatedEvent {
      export type InputTuple = [newMaxSupply: BigNumberish];
      export type OutputTuple = [newMaxSupply: bigint];
      export interface OutputObject {newMaxSupply: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintPriceUpdatedEvent {
      export type InputTuple = [newPrice: BigNumberish];
      export type OutputTuple = [newPrice: bigint];
      export interface OutputObject {newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintedEvent {
      export type InputTuple = [to: AddressLike, tokenId: BigNumberish, title: string, description: string, paymentToken: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, tokenId: bigint, title: string, description: string, paymentToken: string, amount: bigint];
      export interface OutputObject {to: string, tokenId: bigint, title: string, description: string, paymentToken: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentTokenUpdatedEvent {
      export type InputTuple = [newToken: AddressLike];
      export type OutputTuple = [newToken: string];
      export interface OutputObject {newToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenAcceptanceUpdatedEvent {
      export type InputTuple = [token: AddressLike, accepted: boolean];
      export type OutputTuple = [token: string, accepted: boolean];
      export interface OutputObject {token: string, accepted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [from: string, to: string, tokenId: bigint];
      export interface OutputObject {from: string, to: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MintGrindNFT extends BaseContract {
    
    connect(runner?: ContractRunner | null): MintGrindNFT;
    waitForDeployment(): Promise<this>;

    interface: MintGrindNFTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TARGET_CHAIN_ID: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptedTokens: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    balanceOf: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    canMint: TypedContractMethod<
      [user_: AddressLike, quantity_: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    getApproved: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getMintedCount: TypedContractMethod<
      [user_: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRemainingMints: TypedContractMethod<
      [user_: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxPerWallet: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [quantity_: BigNumberish, title_: string, description_: string, token_: AddressLike, expiry_: BigNumberish, signature_: BytesLike, ],
      [void],
      'payable'
    >
    

    
    mintPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mintedPerWallet: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    paymentToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recoverNative: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    recoverToken: TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    remainingSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    "safeTransferFrom(address,address,uint256)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, _data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxSupply: TypedContractMethod<
      [newMaxSupply_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMintPrice: TypedContractMethod<
      [newPrice_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPaymentToken: TypedContractMethod<
      [newToken_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenAcceptance: TypedContractMethod<
      [token_: AddressLike, accepted_: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    usedHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TARGET_CHAIN_ID'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptedTokens'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'canMint'): TypedContractMethod<
      [user_: AddressLike, quantity_: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getApproved'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMintedCount'): TypedContractMethod<
      [user_: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRemainingMints'): TypedContractMethod<
      [user_: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [owner: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxPerWallet'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [quantity_: BigNumberish, title_: string, description_: string, token_: AddressLike, expiry_: BigNumberish, signature_: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'mintPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mintedPerWallet'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paymentToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recoverNative'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recoverToken'): TypedContractMethod<
      [token_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'remainingSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom(address,address,uint256,bytes)'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, _data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxSupply'): TypedContractMethod<
      [newMaxSupply_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMintPrice'): TypedContractMethod<
      [newPrice_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaymentToken'): TypedContractMethod<
      [newToken_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenAcceptance'): TypedContractMethod<
      [token_: AddressLike, accepted_: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usedHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'ConsecutiveTransfer'): TypedContractEvent<ConsecutiveTransferEvent.InputTuple, ConsecutiveTransferEvent.OutputTuple, ConsecutiveTransferEvent.OutputObject>;
getEvent(key: 'MaxSupplyUpdated'): TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
getEvent(key: 'MintPriceUpdated'): TypedContractEvent<MintPriceUpdatedEvent.InputTuple, MintPriceUpdatedEvent.OutputTuple, MintPriceUpdatedEvent.OutputObject>;
getEvent(key: 'Minted'): TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PaymentTokenUpdated'): TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
getEvent(key: 'TokenAcceptanceUpdated'): TypedContractEvent<TokenAcceptanceUpdatedEvent.InputTuple, TokenAcceptanceUpdatedEvent.OutputTuple, TokenAcceptanceUpdatedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'ConsecutiveTransfer(uint256,uint256,address,address)': TypedContractEvent<ConsecutiveTransferEvent.InputTuple, ConsecutiveTransferEvent.OutputTuple, ConsecutiveTransferEvent.OutputObject>;
      ConsecutiveTransfer: TypedContractEvent<ConsecutiveTransferEvent.InputTuple, ConsecutiveTransferEvent.OutputTuple, ConsecutiveTransferEvent.OutputObject>;
    

      'MaxSupplyUpdated(uint256)': TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
      MaxSupplyUpdated: TypedContractEvent<MaxSupplyUpdatedEvent.InputTuple, MaxSupplyUpdatedEvent.OutputTuple, MaxSupplyUpdatedEvent.OutputObject>;
    

      'MintPriceUpdated(uint256)': TypedContractEvent<MintPriceUpdatedEvent.InputTuple, MintPriceUpdatedEvent.OutputTuple, MintPriceUpdatedEvent.OutputObject>;
      MintPriceUpdated: TypedContractEvent<MintPriceUpdatedEvent.InputTuple, MintPriceUpdatedEvent.OutputTuple, MintPriceUpdatedEvent.OutputObject>;
    

      'Minted(address,uint256,string,string,address,uint256)': TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
      Minted: TypedContractEvent<MintedEvent.InputTuple, MintedEvent.OutputTuple, MintedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PaymentTokenUpdated(address)': TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
      PaymentTokenUpdated: TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
    

      'TokenAcceptanceUpdated(address,bool)': TypedContractEvent<TokenAcceptanceUpdatedEvent.InputTuple, TokenAcceptanceUpdatedEvent.OutputTuple, TokenAcceptanceUpdatedEvent.OutputObject>;
      TokenAcceptanceUpdated: TypedContractEvent<TokenAcceptanceUpdatedEvent.InputTuple, TokenAcceptanceUpdatedEvent.OutputTuple, TokenAcceptanceUpdatedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }